### ISSUE TITLE
Error al añadir la extension en chrome

### ISSUE THREAD

**Issue by Lood2222** [bettertwt/bettertwt#1]
Cuando la añado a google chrome me aparece este error, `Esta extensión no aparece en Chrome Web Store y se podría haber añadido sin tu conocimiento. [Más información](https://support.google.com/chrome/?p=ui_remove_non_cws_extensions&hl=es)`. tengo las opciones de desarroyador activado, mi version de chrome es: `Versión 107.0.5304.107 (Build oficial) (64 bits)`

**Comment by v1ctorio** [comment]
Por lo que he visto en truedread/netflix-1080p/issues/67, puede que sea solo una advertencia o que por alguna razón de seguridad no te deje, si es una advertencia simplemente no hagas nada, si sigue desactivada puedes instalar la extensión sin empaquetar.
Para instalar sin empaquetar, en bettertwt/bettertwt dale al botón “Code”, luego “Download Zip” y extrae donde quieras ese zip, en chrome://extensions pulsas “Instalar extensión sin empaquetar” (o algo parecido) y eliges la carpeta dónde hayas descomprimido el zip.

**Comment by Lood2222** [comment]
Muchas gracias, a funcionado!, no era una advertencia, chrome directamente la blockeava y no se podia habilitar, pero al usar el zip a funcionado perfectamente
